### ISSUE TITLE
Part 3 branch does not run as posted

### ISSUE THREAD

**Issue by johngoodleaf** [auser/ng-newsletter-beginner-series#1]
It appears that $http is not injected into the controller. I got a ReferenceError because $http was undefined when attempting to run the code straight from the branch. The parameters on the

``` javascript
app.controller('PlayerController', function($scope, $http) {
```

bit are also different. That is, your post differs from the code in the Part 3 branch, though I don't understand exactly why (why is the second argument not an array?).

**Comment by auser** [comment]
That was a mistake. I pushed the fix and thank you for catching it!

As far as the second argument goes, we'll be diving into dependency injection in the final post, so I didn't want to introduce it too early; however I've updated the branch to use the bracket-notation and will reference it in the final post.
